import countries from '@utils/countries.json'
import countries_flags from '@utils/countries_flags.json'

const ddiArray = [
    { cod: '55', offsetImage: '', name: 'Brasil', mask: '99999-9999' },
    { cod: '351', offsetImage: '', name: 'Portugal', mask: null },
    { cod: '1', offsetImage: '', name: 'United States', mask: null },
    { cod: '93', offsetImage: '', name: 'Afghanistan', mask: ' xxxx-xxxxxx' },
    {
        cod: '358',

        offsetImage: '',
        name: 'Aland Islands',
        mask: ' xxxx xxxxx',
    },
    { cod: '355', offsetImage: '', name: 'Albania', mask: ' xxxx xxxx' },
    { cod: '213', offsetImage: '', name: 'Algeria', mask: ' xxxx xxxxxx' },
    {
        cod: '1684',

        offsetImage: '',
        name: 'American Samoa',
        mask: ' xxxx-xxxx',
    },
    { cod: '376', offsetImage: '', name: 'Andorra', mask: ' xxxx xxxx' },
    { cod: '244', offsetImage: '', name: 'Angola', mask: ' xxxx xxxxxx' },
    { cod: '1264', offsetImage: '', name: 'Anguilla', mask: ' xxxx xxxx' },
    {
        cod: '1268',

        offsetImage: '',
        name: 'Antigua and Barbuda',
        mask: ' xxxx xxxx',
    },
    { cod: '54', offsetImage: '', name: 'Argentina', mask: ' xxxx-xxxxxxx' },
    { cod: '374', offsetImage: '', name: 'Armenia', mask: ' xxxx xxxxx' },
    { cod: '297', offsetImage: '', name: 'Aruba', mask: ' xxxx xxx' },
    { cod: '61', offsetImage: '', name: 'Australia', mask: ' x xxxx xxxx' },
    { cod: '43', offsetImage: '', name: 'Austria', mask: ' xxxx xxxxxx' },
    { cod: '994', offsetImage: '', name: 'Azerbaijan', mask: ' xxxx xxx xxx' },

    { cod: '1242', offsetImage: '', name: 'Bahamas', mask: ' xxxx xxxx' },
    { cod: '973', offsetImage: '', name: 'Bahrain', mask: ' xxxx xxxx' },

    { cod: '880', offsetImage: '', name: 'Bangladesh', mask: ' xxxx xxxxxx' },
    { cod: '1246', offsetImage: '', name: 'Barbados', mask: ' xxxx xxxx' },

    { cod: '375', offsetImage: '', name: 'Belarus', mask: ' xxxx xxx xxx' },
    { cod: '32', offsetImage: '', name: 'Belgium', mask: ' xxx xxx xxx' },
    { cod: '501', offsetImage: '', name: 'Belize', mask: ' xxxx xxxx' },
    { cod: '229', offsetImage: '', name: 'Benin', mask: ' xxxx xxxxx' },
    { cod: '1441', offsetImage: '', name: 'Bermuda', mask: ' xxxx xxxx' },
    { cod: '975', offsetImage: '', name: 'Bhutan', mask: '' },
    { cod: '591', offsetImage: '', name: 'Bolivia', mask: '9-9999-9999' },
    { cod: '599', offsetImage: '', name: 'Bonaire', mask: '' },
    {
        cod: '387',

        offsetImage: '',
        name: 'Bosnia and Herzegovina',
        mask: '999-999-999',
    },
    { cod: '267', offsetImage: '', name: 'Botswana', mask: '' },
    { cod: '1', offsetImage: '', name: 'Canada', mask: '999-999-999' },

    { cod: '238', offsetImage: '', name: 'Cape Verde', mask: '' },
    {
        cod: '345',

        offsetImage: '',
        name: 'Cayman Islands',
        mask: '999-9999',
    },
    {
        cod: '236',

        offsetImage: '',
        name: 'Central African Republic',
        mask: '',
    },
    { cod: '235', offsetImage: '', name: 'Chad', mask: '' },
    { cod: '56', offsetImage: '', name: 'Chile', mask: '99999999' },
    { cod: '86', offsetImage: '', name: 'China', mask: '99999999999' },
    { cod: '61', offsetImage: '', name: 'Christmas Island', mask: '' },
    { cod: '61', offsetImage: '', name: 'Cocos Island', mask: '' },
    { cod: '57', offsetImage: '', name: 'Colombia', mask: '999999999' },
    { cod: '269', offsetImage: '', name: 'Comoros', mask: '' },
    { cod: '682', offsetImage: '', name: 'Cook Islands', mask: '' },
    { cod: '506', offsetImage: '', name: 'Costa Rica', mask: '9999-9999' },
    { cod: '385', offsetImage: '', name: 'Croatia', mask: '999-999-999' },
    { cod: '53', offsetImage: '', name: 'Cuba', mask: '99999999' },
    { cod: '599', offsetImage: '', name: 'Curacao', mask: '' },
    {
        cod: '420',

        offsetImage: '',
        name: 'Czech Republic',
        mask: '999-999-999',
    },
    {
        cod: '243',

        offsetImage: '',
        name: 'Democratic Republic of The Congo',
        mask: '',
    },
    { cod: '45', offsetImage: '', name: 'Denmark', mask: '99999999' },
    { cod: '253', offsetImage: '', name: 'Djibouti', mask: '' },
    { cod: '767', offsetImage: '', name: 'Dominica', mask: '999-9999' },
    {
        cod: '1',

        offsetImage: '',
        name: 'Dominican Republic',
        mask: '999-9999',
    },
    { cod: '670', offsetImage: '', name: 'East Timor', mask: '' },
    { cod: '593', offsetImage: '', name: 'Ecuador', mask: '9999999' },
    { cod: '20', offsetImage: '', name: 'Egypt', mask: '999999999' },
    { cod: '503', offsetImage: '', name: 'El Salvador', mask: '9999-9999' },
    { cod: '44', offsetImage: '', name: 'United Kingdom', mask: '9999999999' },
    { cod: '240', offsetImage: '', name: 'Equatorial Guinea', mask: '' },
    { cod: '291', offsetImage: '', name: 'Eritrea', mask: '' },
    { cod: '372', offsetImage: '', name: 'Estonia', mask: ' 99999999' },
    { cod: '251', offsetImage: '', name: 'Ethiopia', mask: null },
    { cod: '500', offsetImage: '', name: 'Falkland Islands', mask: null },
    { cod: '679', offsetImage: '', name: 'Fiji', mask: null },
    { cod: '358', offsetImage: '', name: 'Finland', mask: null },
    { cod: '33', offsetImage: '', name: 'France', mask: null },
    { cod: '689', offsetImage: '', name: 'French Polynesia', mask: null },
    { cod: '241', offsetImage: '', name: 'Gabon', mask: null },
    { cod: '220', offsetImage: '', name: 'Gambia', mask: null },
    { cod: '995', offsetImage: '', name: 'Georgia', mask: null },
    { cod: '49', offsetImage: '', name: 'Germany', mask: null },
    { cod: '233', offsetImage: '', name: 'Ghana', mask: null },
    { cod: '350', offsetImage: '', name: 'Gibraltar', mask: null },
    { cod: '30', offsetImage: '', name: 'Greece', mask: null },
    { cod: '299', offsetImage: '', name: 'Greenland', mask: null },
    { cod: '1473', offsetImage: '', name: 'Grenada', mask: null },
    { cod: '1671', offsetImage: '', name: 'Guam', mask: null },
    { cod: '502', offsetImage: '', name: 'Guatemala', mask: null },
    { cod: '44', offsetImage: '', name: 'Guernsey', mask: null },
    { cod: '224', offsetImage: '', name: 'Guinea', mask: null },
    { cod: '245', offsetImage: '', name: 'Guinea-Bissau', mask: null },
    { cod: '509', offsetImage: '', name: 'Haiti', mask: null },
    { cod: '504', offsetImage: '', name: 'Honduras', mask: null },
    { cod: '852', offsetImage: '', name: 'Hong Kong', mask: null },
    { cod: '36', offsetImage: '', name: 'Hungary', mask: null },
    { cod: '354', offsetImage: '', name: 'Iceland', mask: null },
    { cod: '91', offsetImage: '', name: 'India', mask: null },
    { cod: '62', offsetImage: '', name: 'Indonesia', mask: null },
    { cod: '98', offsetImage: '', name: 'Iran', mask: null },
    { cod: '964', offsetImage: '', name: 'Iraq', mask: null },
    { cod: '353', offsetImage: '', name: 'Ireland', mask: null },
    { cod: '1624', offsetImage: '', name: 'Isle of Man', mask: null },
    { cod: '972', offsetImage: '', name: 'Israel', mask: null },
    { cod: '39', offsetImage: '', name: 'Italy', mask: null },
    { cod: '225', offsetImage: '', name: 'Ivory Coast', mask: null },
    { cod: '1876', offsetImage: '', name: 'Jamaica', mask: null },
    { cod: '81', offsetImage: '', name: 'Japan', mask: null },
    { cod: '44', offsetImage: '', name: 'Jersey', mask: null },
    { cod: '962', offsetImage: '', name: 'Jordan', mask: null },
    { cod: '7', offsetImage: '', name: 'Kazakhstan', mask: null },
    { cod: '254', offsetImage: '', name: 'Kenya', mask: null },
    { cod: '686', offsetImage: '', name: 'Kiribati', mask: null },
    { cod: '965', offsetImage: '', name: 'Kuwait', mask: null },
    { cod: '996', offsetImage: '', name: 'Kyrgyzstan', mask: null },
    { cod: '856', offsetImage: '', name: 'Laos', mask: null },
    { cod: '371', offsetImage: '', name: 'Latvia', mask: null },
    { cod: '961', offsetImage: '', name: 'Lebanon', mask: null },
    { cod: '266', offsetImage: '', name: 'Lesotho', mask: null },
    { cod: '231', offsetImage: '', name: 'Liberia', mask: null },
    { cod: '218', offsetImage: '', name: 'Libya', mask: null },
    { cod: '423', offsetImage: '', name: 'Liechtenstein', mask: null },
    { cod: '370', offsetImage: '', name: 'Lithuania', mask: null },
    { cod: '352', offsetImage: '', name: 'Luxembourg', mask: null },
    { cod: '853', offsetImage: '', name: 'Macao', mask: null },
    { cod: '261', offsetImage: '', name: 'Madagascar', mask: null },
    { cod: '60', offsetImage: '', name: 'Malaysia', mask: null },
    { cod: '265', offsetImage: '', name: 'Malawi', mask: null },
    { cod: '960', offsetImage: '', name: 'Maldives', mask: null },
    { cod: '223', offsetImage: '', name: 'Mali', mask: null },
    { cod: '356', offsetImage: '', name: 'Malta', mask: null },
    { cod: '692', offsetImage: '', name: 'Marshall Islands', mask: null },
    { cod: '596', offsetImage: '', name: 'Martinique', mask: null },
    { cod: '222', offsetImage: '', name: 'Mauritania', mask: null },
    { cod: '230', offsetImage: '', name: 'Mauritius', mask: null },
    { cod: '52', offsetImage: '', name: 'Mexico', mask: null },
    { cod: '691', offsetImage: '', name: 'Micronesia', mask: null },
    { cod: '373', offsetImage: '', name: 'Moldova', mask: null },
    { cod: '377', offsetImage: '', name: 'Monaco', mask: null },
    { cod: '976', offsetImage: '', name: 'Mongolia', mask: null },
    { cod: '382', offsetImage: '', name: 'Montenegro', mask: null },
    { cod: '664', offsetImage: '', name: 'Montserrat', mask: null },
    { cod: '212', offsetImage: '', name: 'Morocco', mask: null },
    { cod: '258', offsetImage: '', name: 'Mozambique', mask: null },
    { cod: '95', offsetImage: '', name: 'Myanmar', mask: null },
    { cod: '264', offsetImage: '', name: 'Namibia', mask: null },
    { cod: '674', offsetImage: '', name: 'Nauru', mask: null },
    { cod: '977', offsetImage: '', name: 'Nepal', mask: null },
    { cod: '31', offsetImage: '', name: 'Netherlands', mask: null },
    { cod: '64', offsetImage: '', name: 'New Zealand', mask: null },
    { cod: '505', offsetImage: '', name: 'Nicaragua', mask: null },
    { cod: '227', offsetImage: '', name: 'Niger', mask: null },
    { cod: '234', offsetImage: '', name: 'Nigeria', mask: null },
    { cod: '683', offsetImage: '', name: 'Niue', mask: null },
    { cod: '672', offsetImage: '', name: 'Norfolk Island', mask: null },
    {
        cod: '1670',
        offsetImage: '',
        name: 'Northern Mariana Islands',
        mask: null,
    },
    { cod: '850', offsetImage: '', name: 'North Korea', mask: null },
    { cod: '47', offsetImage: '', name: 'Norway', mask: null },
    { cod: '968', offsetImage: '', name: 'Oman', mask: null },
    { cod: '92', offsetImage: '', name: 'Pakistan', mask: null },
    { cod: '680', offsetImage: '', name: 'Palau', mask: null },
    { cod: '970', offsetImage: '', name: 'Palestine', mask: null },
    { cod: '507', offsetImage: '', name: 'Panama', mask: null },
    { cod: '675', offsetImage: '', name: 'Papua New Guinea', mask: null },
    { cod: '595', offsetImage: '', name: 'Paraguay', mask: null },
    { cod: '51', offsetImage: '', name: 'Peru', mask: null },
    { cod: '63', offsetImage: '', name: 'Philippines', mask: null },
    { cod: '872', offsetImage: '', name: 'Pitcairn Islands', mask: null },
    { cod: '48', offsetImage: '', name: 'Poland', mask: null },
    { cod: '1', offsetImage: '', name: 'Puerto Rico', mask: null },
    { cod: '974', offsetImage: '', name: 'Qatar', mask: null },
    {
        cod: '389',
        offsetImage: '',
        name: 'Macedonia',
        mask: null,
    },
    {
        cod: '242',

        offsetImage: '',
        name: 'Republic Of The Congo',
        mask: null,
    },
    { cod: '40', offsetImage: '', name: 'Romania', mask: null },
    { cod: '7', offsetImage: '', name: 'Russia', mask: null },
    { cod: '250', offsetImage: '', name: 'Rwanda', mask: null },
    {
        cod: '212',

        offsetImage: '',
        name: 'Sahrawi Arab Democratic Republic',
        mask: null,
    },

    { cod: '685', offsetImage: '', name: 'Samoa', mask: null },
    { cod: '378', offsetImage: '', name: 'San Marino', mask: null },
    {
        cod: '239',

        offsetImage: '',
        name: 'Sao Tome and Principe',
        mask: null,
    },
    { cod: '966', offsetImage: '', name: 'Saudi Arabia', mask: null },
    { cod: '221', offsetImage: '', name: 'Senegal', mask: null },
    { cod: '381', offsetImage: '', name: 'Serbia', mask: null },
    { cod: '248', offsetImage: '', name: 'Seychelles', mask: null },
    { cod: '232', offsetImage: '', name: 'Sierra Leone', mask: null },
    { cod: '65', offsetImage: '', name: 'Singapore', mask: null },
    { cod: '1721', offsetImage: '', name: 'Sint Maarten', mask: null },
    { cod: '421', offsetImage: '', name: 'Slovakia', mask: null },
    { cod: '386', offsetImage: '', name: 'Slovenia', mask: null },
    { cod: '677', offsetImage: '', name: 'Solomon Islands', mask: null },
    { cod: '252', offsetImage: '', name: 'Somalia', mask: null },
    { cod: '27', offsetImage: '', name: 'South Africa', mask: null },
    { cod: '82', offsetImage: '', name: 'South Korea', mask: null },
    { cod: '211', offsetImage: '', name: 'South Sudan', mask: null },
    { cod: '34', offsetImage: '', name: 'Spain', mask: null },
    { cod: '94', offsetImage: '', name: 'Sri Lanka', mask: null },
    { cod: '590', offsetImage: '', name: 'St Barts', mask: null },
    { cod: '249', offsetImage: '', name: 'Sudan', mask: null },
    { cod: '597', offsetImage: '', name: 'Suriname', mask: null },
    { cod: '268', offsetImage: '', name: 'Swaziland', mask: null },
    { cod: '46', offsetImage: '', name: 'Sweden', mask: null },
    { cod: '41', offsetImage: '', name: 'Switzerland', mask: null },
    { cod: '963', offsetImage: '', name: 'Syria', mask: null },
    { cod: '886', offsetImage: '', name: 'Taiwan', mask: null },
    { cod: '992', offsetImage: '', name: 'Tajikistan', mask: null },
    { cod: '255', offsetImage: '', name: 'Tanzania', mask: null },
    { cod: '66', offsetImage: '', name: 'Thailand', mask: null },
    { cod: '228', offsetImage: '', name: 'Togo', mask: null },
    { cod: '690', offsetImage: '', name: 'Tokelau', mask: null },
    { cod: '676', offsetImage: '', name: 'Tonga', mask: null },

    {
        cod: '1868',

        offsetImage: '',
        name: 'Trinidad and Tobago',
        mask: null,
    },
    { cod: '216', offsetImage: '', name: 'Tunisia', mask: null },
    { cod: '90', offsetImage: '', name: 'Turkey', mask: null },
    { cod: '993', offsetImage: '', name: 'Turkmenistan', mask: null },
    { cod: '1', offsetImage: '', name: 'Turks and Caicos Islands', mask: null },
    { cod: '688', offsetImage: '', name: 'Tuvalu', mask: null },
    { cod: '256', offsetImage: '', name: 'Uganda', mask: null },
    { cod: '380', offsetImage: '', name: 'Ukraine', mask: null },
    {
        cod: '971',
        offsetImage: '',
        name: 'United Arab Emirates',
        mask: null,
    },
    { cod: '44', offsetImage: '', name: 'United Kingdom', mask: null },
    { cod: '598', offsetImage: '', name: 'Uruguay', mask: null },
    { cod: '998', offsetImage: '', name: 'Uzbekistan', mask: null },
    { cod: '678', offsetImage: '', name: 'Vanuatu', mask: null },
    { cod: '0', offsetImage: '', name: 'Vatican City', mask: null },
    { cod: '58', offsetImage: '', name: 'Venezuela', mask: null },
    { cod: '84', offsetImage: '', name: 'Vietnam', mask: null },
    { cod: '1', offsetImage: '', name: 'Virgin Islands', mask: null },
    { cod: '967', offsetImage: '', name: 'Yemen', mask: null },
    { cod: '260', offsetImage: '', name: 'Zambia', mask: null },
    { cod: '263', offsetImage: '', name: 'Zimbabwe', mask: ' xxxx-xxxx' },
]

export default ddiArray.map((countrie, index) => {
    const countryObject = countries.filter((country) => country.name == countrie.name)
    /* @ts-ignore */
    countrie.offsetImage = `data:image/png;base64,${countries_flags[(countryObject[0]?.iso2)?.toLocaleLowerCase()]}`
    return countrie
})
